-- Ajouter les nouveaux champs pour le formulaire complet de dossier contentieux
ALTER TABLE public.affaires
ADD COLUMN region TEXT,
ADD COLUMN office TEXT,
ADD COLUMN num_declaration TEXT,
ADD COLUMN date_declaration DATE,
ADD COLUMN nom_prenom_contrevenant TEXT,
ADD COLUMN adresse_complete TEXT,
ADD COLUMN ifu TEXT,
ADD COLUMN nature_et_moyen_de_transport TEXT,
ADD COLUMN identification_mt TEXT,
ADD COLUMN commissionnaire_en_d TEXT,
ADD COLUMN procede_de_detection TEXT,
ADD COLUMN nombre INTEGER,
ADD COLUMN nature_des_marchandises_de_fraude TEXT,
ADD COLUMN origine_ou_provenance TEXT,
ADD COLUMN valeur_des_marchandises_litigieuses INTEGER,
ADD COLUMN nature_de_l_infraction TEXT,
ADD COLUMN droits_compromis_ou_eludes INTEGER,
ADD COLUMN num_quittance_dce TEXT,
ADD COLUMN composition_dossier TEXT,
ADD COLUMN circonstances TEXT,
ADD COLUMN nombre_informateurs INTEGER DEFAULT 0,
ADD COLUMN suite_de_l_affaire TEXT,
ADD COLUMN date_de_la_transaction_provisoire DATE,
ADD COLUMN montant_amende_ou_vente INTEGER,
ADD COLUMN num_quittance TEXT,
ADD COLUMN date_quittance DATE,
ADD COLUMN montant_total_des_frais INTEGER DEFAULT 0,
ADD COLUMN noms_des_chefs TEXT,
ADD COLUMN nom_saisissants TEXT,
ADD COLUMN nom_intervenants TEXT,
ADD COLUMN suite_reservee_aux_mdses TEXT,
ADD COLUMN notes_supplementaires TEXT;